@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

Container(Frontend, "Frontend", "JS ofzo")
Container_Boundary(Backend, "Backend")
Component(Controller, "controller (bv. booking)", "Java Spring Controller", "Een controller die gebruik maakt van een externe API in zijn process")
Component(Service, "Service", "Java Spring Service", "het service component dat gebruikt wordt in dit process")
Component(ExternalController, "External API Controller", "Java Spring Controller", "Controller die verantwoordelijk is voor externe API calls")
Component(ErrorHandler, "External API Error Handler", "custom Error handler", "Verwerkt wat de error is en geeft een waardevolle response element terug")
Boundary_End()
Component(ExternalAPI, "External API")

Rel(Frontend, Controller, "")
Rel(Controller, Service, "")
Rel(Service, ExternalController, "")
Rel(ExternalController, ExternalAPI , "Called")
Rel(ExternalAPI, ExternalController, "Responds (or doesnt) with error")
Rel(ExternalController, ErrorHandler, "Delegeert error handling naar")
Rel(ErrorHandler, ExternalController, "Geeft waardevolle response element")
Rel(ExternalController, Service, "returnt dat er een error is en de bijhoorde response entity")
Rel(Service, Controller, "returnt response entity")
Rel(Controller, Frontend, "returnt response entity")
@enduml