@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

top to bottom direction

Actor(user, "User", "Handles user login")


Container_Boundary(Frontend, "Frontend component-diagram") {

Component(enterExpenseClaim, "Enter Expense Claim", "React Component", "Handles expense claim entry")
Component(Login, "Login", "React Component", "Handles user login")
Component(Logout, "Logout", "React Component", "Handles user logout")
Component(RetrieveExpenseClaim, "Retrieve Expense Claim", "React Component", "Handles expense claim retrieval")


Rel(enterExpenseClaim, Login, "Uses")
Rel(Login, RetrieveExpenseClaim, "Uses")
Rel(RetrieveExpenseClaim, Logout, "Uses")



}

Container(backend, "Backend", "Java Spring Boot")

@enduml
